--CREATE DATABASE IF NOT EXISTS resavedb;

DROP TABLE IF EXISTS file_name;
DROP TABLE IF EXISTS person;

CREATE TABLE IF NOT EXISTS person (
  id SERIAL PRIMARY KEY,
  first_name CHARACTER VARYING(100) NOT NULL,
  last_name CHARACTER VARYING(100) NOT NULL,
  country CHARACTER VARYING(100) NOT NULL,
  city CHARACTER VARYING(100) NOT NULL
 );

CREATE TABLE IF NOT EXISTS file_name (
  id int NOT NULL PRIMARY KEY,
  file_path CHARACTER VARYING(250) NOT NULL
 );

INSERT INTO file_name VALUES (1, './src/main/resources/person');